# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiSlit.ui'
#
# Created: Wed Jan 27 10:42:59 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(640, 450)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(200, 10, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label.setObjectName("label")
        self.labelTopPosition = QtGui.QLabel(self.groupBox)
        self.labelTopPosition.setGeometry(QtCore.QRect(30, 60, 91, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelTopPosition.setFont(font)
        self.labelTopPosition.setObjectName("labelTopPosition")
        self.tbTopOpen = QtGui.QToolButton(self.groupBox)
        self.tbTopOpen.setGeometry(QtCore.QRect(150, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbTopOpen.setFont(font)
        self.tbTopOpen.setObjectName("tbTopOpen")
        self.tbTopClose = QtGui.QToolButton(self.groupBox)
        self.tbTopClose.setGeometry(QtCore.QRect(150, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbTopClose.setFont(font)
        self.tbTopClose.setObjectName("tbTopClose")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 300, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label_4.setObjectName("label_4")
        self.labelBottomPosition = QtGui.QLabel(self.groupBox_2)
        self.labelBottomPosition.setGeometry(QtCore.QRect(30, 60, 91, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelBottomPosition.setFont(font)
        self.labelBottomPosition.setObjectName("labelBottomPosition")
        self.tbBottomClose = QtGui.QToolButton(self.groupBox_2)
        self.tbBottomClose.setGeometry(QtCore.QRect(150, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbBottomClose.setFont(font)
        self.tbBottomClose.setObjectName("tbBottomClose")
        self.tbBottomOpen = QtGui.QToolButton(self.groupBox_2)
        self.tbBottomOpen.setGeometry(QtCore.QRect(150, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbBottomOpen.setFont(font)
        self.tbBottomOpen.setObjectName("tbBottomOpen")
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(4, 150, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 101, 41))
        self.label_5.setObjectName("label_5")
        self.labelOutboardPosition = QtGui.QLabel(self.groupBox_3)
        self.labelOutboardPosition.setGeometry(QtCore.QRect(90, 40, 91, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelOutboardPosition.setFont(font)
        self.labelOutboardPosition.setObjectName("labelOutboardPosition")
        self.tbOutboardOpen = QtGui.QToolButton(self.groupBox_3)
        self.tbOutboardOpen.setGeometry(QtCore.QRect(30, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbOutboardOpen.setFont(font)
        self.tbOutboardOpen.setObjectName("tbOutboardOpen")
        self.tbOutboardClose = QtGui.QToolButton(self.groupBox_3)
        self.tbOutboardClose.setGeometry(QtCore.QRect(130, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbOutboardClose.setFont(font)
        self.tbOutboardClose.setObjectName("tbOutboardClose")
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 150, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 101, 41))
        self.label_6.setObjectName("label_6")
        self.labelInboardPosition = QtGui.QLabel(self.groupBox_4)
        self.labelInboardPosition.setGeometry(QtCore.QRect(90, 40, 91, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelInboardPosition.setFont(font)
        self.labelInboardPosition.setObjectName("labelInboardPosition")
        self.tbInboardClose = QtGui.QToolButton(self.groupBox_4)
        self.tbInboardClose.setGeometry(QtCore.QRect(30, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbInboardClose.setFont(font)
        self.tbInboardClose.setObjectName("tbInboardClose")
        self.tbInboardOpen = QtGui.QToolButton(self.groupBox_4)
        self.tbInboardOpen.setGeometry(QtCore.QRect(130, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.tbInboardOpen.setFont(font)
        self.tbInboardOpen.setObjectName("tbInboardOpen")
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(200, 160, 231, 141))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(14, 12, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox.setGeometry(QtCore.QRect(70, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.pbOpenAll = QtGui.QPushButton(self.groupBox_5)
        self.pbOpenAll.setGeometry(QtCore.QRect(10, 77, 93, 41))
        self.pbOpenAll.setObjectName("pbOpenAll")
        self.pbCloseAll = QtGui.QPushButton(self.groupBox_5)
        self.pbCloseAll.setGeometry(QtCore.QRect(125, 77, 93, 40))
        self.pbCloseAll.setObjectName("pbCloseAll")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Slit control", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTopPosition.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTopOpen.setText(QtGui.QApplication.translate("Dialog", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTopClose.setText(QtGui.QApplication.translate("Dialog", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBottomPosition.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBottomClose.setText(QtGui.QApplication.translate("Dialog", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBottomOpen.setText(QtGui.QApplication.translate("Dialog", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Outboard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutboardPosition.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOutboardOpen.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOutboardClose.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Inboard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInboardPosition.setText(QtGui.QApplication.translate("Dialog", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.tbInboardClose.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.tbInboardOpen.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "micron", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOpenAll.setText(QtGui.QApplication.translate("Dialog", "Open All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCloseAll.setText(QtGui.QApplication.translate("Dialog", "Close All", None, QtGui.QApplication.UnicodeUTF8))

