#!/bin/bash -i
#
# Deactivate conda so that it doens't interfer with things
for i in $(seq ${CONDA_SHLVL}); do
    eval "conda deactivate"
done

source /usr/local/source_epics.sh

pushd /usr/local/ImageJ
java -jar ij.jar
popd
