# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMarCCD.ui'
#
# Created: Thu Mar 24 09:43:39 2016
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgSampleCCD(object):
    def setupUi(self, dlgSampleCCD):
        dlgSampleCCD.setObjectName("dlgSampleCCD")
        dlgSampleCCD.resize(594, 555)
        font = QtGui.QFont()
        font.setPointSize(14)
        dlgSampleCCD.setFont(font)
        self.groupBox_2 = QtGui.QGroupBox(dlgSampleCCD)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 571, 211))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 105, 441, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 139, 381, 16))
        self.label_8.setObjectName("label_8")
        self.leSampleCode = QtGui.QLineEdit(self.groupBox_2)
        self.leSampleCode.setGeometry(QtCore.QRect(460, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.leSampleCode.setFont(font)
        self.leSampleCode.setObjectName("leSampleCode")
        self.leSampleDescription = QtGui.QLineEdit(self.groupBox_2)
        self.leSampleDescription.setGeometry(QtCore.QRect(20, 169, 541, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.leSampleDescription.setFont(font)
        self.leSampleDescription.setObjectName("leSampleDescription")
        self.leDataFolder = QtGui.QLineEdit(self.groupBox_2)
        self.leDataFolder.setGeometry(QtCore.QRect(20, 60, 531, 29))
        self.leDataFolder.setObjectName("leDataFolder")
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 171, 20))
        self.label_13.setObjectName("label_13")
        self.groupBox_3 = QtGui.QGroupBox(dlgSampleCCD)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 571, 221))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(207, 40, 201, 16))
        self.label_11.setObjectName("label_11")
        self.dsbExposureTime = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsbExposureTime.setGeometry(QtCore.QRect(397, 38, 111, 31))
        self.dsbExposureTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbExposureTime.setDecimals(3)
        self.dsbExposureTime.setMinimum(0.01)
        self.dsbExposureTime.setMaximum(99999.99)
        self.dsbExposureTime.setProperty("value", 1.0)
        self.dsbExposureTime.setObjectName("dsbExposureTime")
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(207, 90, 201, 16))
        self.label_12.setObjectName("label_12")
        self.sbNumberOfFrames = QtGui.QSpinBox(self.groupBox_3)
        self.sbNumberOfFrames.setGeometry(QtCore.QRect(397, 80, 111, 31))
        self.sbNumberOfFrames.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbNumberOfFrames.setMinimum(1)
        self.sbNumberOfFrames.setMaximum(99999)
        self.sbNumberOfFrames.setObjectName("sbNumberOfFrames")
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(210, 130, 181, 16))
        self.label_14.setObjectName("label_14")
        self.lblDetectorStatus = QtGui.QLabel(self.groupBox_3)
        self.lblDetectorStatus.setGeometry(QtCore.QRect(407, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.lblDetectorStatus.setFont(font)
        self.lblDetectorStatus.setStyleSheet("color:green")
        self.lblDetectorStatus.setObjectName("lblDetectorStatus")
        self.pbStartMarCCD = QtGui.QPushButton(self.groupBox_3)
        self.pbStartMarCCD.setGeometry(QtCore.QRect(330, 160, 141, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pbStartMarCCD.setFont(font)
        self.pbStartMarCCD.setStyleSheet("")
        self.pbStartMarCCD.setObjectName("pbStartMarCCD")
        self.pbTakeDark = QtGui.QPushButton(self.groupBox_3)
        self.pbTakeDark.setGeometry(QtCore.QRect(20, 40, 141, 41))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pbTakeDark.setFont(font)
        self.pbTakeDark.setStyleSheet("")
        self.pbTakeDark.setObjectName("pbTakeDark")
        self.dteNow = QtGui.QDateTimeEdit(dlgSampleCCD)
        self.dteNow.setGeometry(QtCore.QRect(10, 492, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.dteNow.setFont(font)
        self.dteNow.setReadOnly(True)
        self.dteNow.setDate(QtCore.QDate(2016, 3, 10))
        self.dteNow.setTime(QtCore.QTime(13, 0, 0))
        self.dteNow.setMaximumTime(QtCore.QTime(22, 59, 59))
        self.dteNow.setObjectName("dteNow")
        self.line = QtGui.QFrame(dlgSampleCCD)
        self.line.setGeometry(QtCore.QRect(10, 470, 571, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_15 = QtGui.QLabel(dlgSampleCCD)
        self.label_15.setGeometry(QtCore.QRect(330, 520, 221, 31))
        self.label_15.setObjectName("label_15")
        self.lblStorageRingCurrent = QtGui.QLabel(dlgSampleCCD)
        self.lblStorageRingCurrent.setGeometry(QtCore.QRect(480, 510, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.lblStorageRingCurrent.setFont(font)
        self.lblStorageRingCurrent.setStyleSheet("color:green")
        self.lblStorageRingCurrent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblStorageRingCurrent.setIndent(0)
        self.lblStorageRingCurrent.setObjectName("lblStorageRingCurrent")
        self.label_9 = QtGui.QLabel(dlgSampleCCD)
        self.label_9.setGeometry(QtCore.QRect(330, 490, 171, 21))
        self.label_9.setObjectName("label_9")
        self.lblRunNumber = QtGui.QLabel(dlgSampleCCD)
        self.lblRunNumber.setGeometry(QtCore.QRect(490, 490, 101, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblRunNumber.setFont(font)
        self.lblRunNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRunNumber.setObjectName("lblRunNumber")

        self.retranslateUi(dlgSampleCCD)
        QtCore.QMetaObject.connectSlotsByName(dlgSampleCCD)
        dlgSampleCCD.setTabOrder(self.leDataFolder, self.leSampleCode)
        dlgSampleCCD.setTabOrder(self.leSampleCode, self.leSampleDescription)
        dlgSampleCCD.setTabOrder(self.leSampleDescription, self.dsbExposureTime)
        dlgSampleCCD.setTabOrder(self.dsbExposureTime, self.sbNumberOfFrames)
        dlgSampleCCD.setTabOrder(self.sbNumberOfFrames, self.pbStartMarCCD)
        dlgSampleCCD.setTabOrder(self.pbStartMarCCD, self.dteNow)

    def retranslateUi(self, dlgSampleCCD):
        dlgSampleCCD.setWindowTitle(QtGui.QApplication.translate("dlgSampleCCD", "MarCCD experiment control ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgSampleCCD", "Sample Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgSampleCCD", "Sample code (keep short, best < 8 characters):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlgSampleCCD", "Sample description (< 80 characters):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("dlgSampleCCD", "Log file full path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dlgSampleCCD", "MarCCD detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("dlgSampleCCD", "Exposure time (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("dlgSampleCCD", "Number of frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("dlgSampleCCD", "Detector status:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDetectorStatus.setText(QtGui.QApplication.translate("dlgSampleCCD", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStartMarCCD.setText(QtGui.QApplication.translate("dlgSampleCCD", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTakeDark.setText(QtGui.QApplication.translate("dlgSampleCCD", "Take Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.dteNow.setDisplayFormat(QtGui.QApplication.translate("dlgSampleCCD", "MM/dd/yyyy hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("dlgSampleCCD", "Ring current (mA):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStorageRingCurrent.setText(QtGui.QApplication.translate("dlgSampleCCD", "102.2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dlgSampleCCD", "Run number:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRunNumber.setText(QtGui.QApplication.translate("dlgSampleCCD", "----", None, QtGui.QApplication.UnicodeUTF8))

