# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiScanGrid.ui'
#
# Created: Fri Jul 22 18:33:58 2016
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgScanGrid(object):
    def setupUi(self, dlgScanGrid):
        dlgScanGrid.setObjectName("dlgScanGrid")
        dlgScanGrid.resize(584, 401)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        dlgScanGrid.setFont(font)
        self.pbStartScan = QtGui.QPushButton(dlgScanGrid)
        self.pbStartScan.setGeometry(QtCore.QRect(120, 371, 83, 24))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pbStartScan.setFont(font)
        self.pbStartScan.setObjectName("pbStartScan")
        self.pbAbortScan = QtGui.QPushButton(dlgScanGrid)
        self.pbAbortScan.setGeometry(QtCore.QRect(370, 370, 83, 24))
        self.pbAbortScan.setCursor(QtCore.Qt.OpenHandCursor)
        self.pbAbortScan.setObjectName("pbAbortScan")
        self.groupBox = QtGui.QGroupBox(dlgScanGrid)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 561, 61))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(19, 32, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(204, 31, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(380, 30, 61, 16))
        self.label_3.setObjectName("label_3")
        self.dsbXstart = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsbXstart.setGeometry(QtCore.QRect(70, 30, 121, 31))
        self.dsbXstart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbXstart.setDecimals(3)
        self.dsbXstart.setMinimum(-200.0)
        self.dsbXstart.setMaximum(200.0)
        self.dsbXstart.setSingleStep(0.005)
        self.dsbXstart.setProperty("value", -9.375)
        self.dsbXstart.setObjectName("dsbXstart")
        self.dsbXend = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsbXend.setGeometry(QtCore.QRect(240, 30, 121, 31))
        self.dsbXend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbXend.setDecimals(3)
        self.dsbXend.setMinimum(-200.0)
        self.dsbXend.setMaximum(200.0)
        self.dsbXend.setSingleStep(0.005)
        self.dsbXend.setProperty("value", 14.25)
        self.dsbXend.setObjectName("dsbXend")
        self.dsbXstep = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsbXstep.setGeometry(QtCore.QRect(430, 30, 121, 31))
        self.dsbXstep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbXstep.setDecimals(3)
        self.dsbXstep.setMinimum(-200.0)
        self.dsbXstep.setMaximum(200.0)
        self.dsbXstep.setSingleStep(0.005)
        self.dsbXstep.setProperty("value", 1.5)
        self.dsbXstep.setObjectName("dsbXstep")
        self.groupBox_2 = QtGui.QGroupBox(dlgScanGrid)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 561, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(19, 32, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(204, 31, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(380, 30, 61, 16))
        self.label_6.setObjectName("label_6")
        self.dsbYstart = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsbYstart.setGeometry(QtCore.QRect(70, 30, 121, 31))
        self.dsbYstart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbYstart.setDecimals(3)
        self.dsbYstart.setMinimum(-200.0)
        self.dsbYstart.setMaximum(200.0)
        self.dsbYstart.setSingleStep(0.005)
        self.dsbYstart.setProperty("value", -0.5)
        self.dsbYstart.setObjectName("dsbYstart")
        self.dsbYend = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsbYend.setGeometry(QtCore.QRect(240, 30, 131, 31))
        self.dsbYend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbYend.setDecimals(3)
        self.dsbYend.setMinimum(-200.0)
        self.dsbYend.setMaximum(200.0)
        self.dsbYend.setSingleStep(0.005)
        self.dsbYend.setProperty("value", -0.22)
        self.dsbYend.setObjectName("dsbYend")
        self.dsbYstep = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsbYstep.setGeometry(QtCore.QRect(430, 30, 131, 31))
        self.dsbYstep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbYstep.setDecimals(3)
        self.dsbYstep.setMinimum(-200.0)
        self.dsbYstep.setMaximum(200.0)
        self.dsbYstep.setSingleStep(0.005)
        self.dsbYstep.setProperty("value", 0.01)
        self.dsbYstep.setObjectName("dsbYstep")
        self.label_7 = QtGui.QLabel(dlgScanGrid)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 421, 16))
        self.label_7.setObjectName("label_7")
        self.leScanName = QtGui.QLineEdit(dlgScanGrid)
        self.leScanName.setGeometry(QtCore.QRect(460, 160, 113, 20))
        self.leScanName.setObjectName("leScanName")
        self.leScanRemark = QtGui.QLineEdit(dlgScanGrid)
        self.leScanRemark.setGeometry(QtCore.QRect(14, 210, 561, 20))
        self.leScanRemark.setObjectName("leScanRemark")
        self.label_8 = QtGui.QLabel(dlgScanGrid)
        self.label_8.setGeometry(QtCore.QRect(13, 190, 381, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtGui.QGroupBox(dlgScanGrid)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 561, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lblStatusText = QtGui.QLabel(self.groupBox_3)
        self.lblStatusText.setGeometry(QtCore.QRect(20, 90, 531, 21))
        self.lblStatusText.setAutoFillBackground(False)
        self.lblStatusText.setObjectName("lblStatusText")
        self.lblMotorPosition = QtGui.QLabel(self.groupBox_3)
        self.lblMotorPosition.setGeometry(QtCore.QRect(20, 60, 521, 21))
        self.lblMotorPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMotorPosition.setObjectName("lblMotorPosition")
        self.lblScanName = QtGui.QLabel(self.groupBox_3)
        self.lblScanName.setGeometry(QtCore.QRect(20, 30, 521, 21))
        self.lblScanName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblScanName.setObjectName("lblScanName")

        self.retranslateUi(dlgScanGrid)
        QtCore.QMetaObject.connectSlotsByName(dlgScanGrid)
        dlgScanGrid.setTabOrder(self.dsbXstart, self.dsbXend)
        dlgScanGrid.setTabOrder(self.dsbXend, self.dsbXstep)
        dlgScanGrid.setTabOrder(self.dsbXstep, self.dsbYstart)
        dlgScanGrid.setTabOrder(self.dsbYstart, self.dsbYend)
        dlgScanGrid.setTabOrder(self.dsbYend, self.dsbYstep)
        dlgScanGrid.setTabOrder(self.dsbYstep, self.leScanName)
        dlgScanGrid.setTabOrder(self.leScanName, self.leScanRemark)
        dlgScanGrid.setTabOrder(self.leScanRemark, self.pbStartScan)
        dlgScanGrid.setTabOrder(self.pbStartScan, self.pbAbortScan)

    def retranslateUi(self, dlgScanGrid):
        dlgScanGrid.setWindowTitle(QtGui.QApplication.translate("dlgScanGrid", "2D grid scan for laminar flow SAXS", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStartScan.setText(QtGui.QApplication.translate("dlgScanGrid", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAbortScan.setText(QtGui.QApplication.translate("dlgScanGrid", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgScanGrid", "X (horizontal direction along the channel)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgScanGrid", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgScanGrid", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgScanGrid", "step", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgScanGrid", "Y (vertical direction across the channel)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgScanGrid", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgScanGrid", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgScanGrid", "step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgScanGrid", "Scan name (keep short, best < 8 characters):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlgScanGrid", "Scan description (< 80 characters):", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dlgScanGrid", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatusText.setText(QtGui.QApplication.translate("dlgScanGrid", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMotorPosition.setText(QtGui.QApplication.translate("dlgScanGrid", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScanName.setText(QtGui.QApplication.translate("dlgScanGrid", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

